export { default as Page_404 } from './404/Page_404'
export { default as Explore } from './explore/Explore'
export { default as Home } from './home/Home'
export { default as Details } from './details/Details'
export { default as CastDetails } from './castDetails/CastDetails'
export { default as SearchResults } from './searchResult/SearchResults'
export { default as AuthPage } from './authPage/AuthPage'